apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scheduler-claim.code
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: slow
  volumeName: scheduler.code
