apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim.data
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: slow
  volumeName: db.data
