apiVersion: v1
kind: PersistentVolume
metadata:
  name: uwsgi.static
spec:
  capacity:
    storage: 60Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  nfs:
    path: /mnt/nfs_share/sregistry/static
    server: 192.52.41.171
