apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uwsgi-claim.images
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: slow
  volumeName: uwsgi.images
