apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx.ssl
spec:
  capacity:
    storage: 60Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: slow
  nfs:
    path: /mnt/nfs_share/sregistry/ssl
    server: 192.52.41.171
