apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim.nginx-files
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: slow
  volumeName: nginx.nginx-files
