name: Build and Deploy Container

on:
  # Publish packages on release
  release:
    types: [published]

  pull_request: []
  workflow_dispatch:

  # On push to main we build and deploy images
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      packages: write

    env:
      container: ghcr.io/singularityhub/sregistry
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Container
        run: |
          docker build -t ${{ env.container }}:latest .
          cd ./nginx
          docker build -t ${{ env.container }}_nginx:latest .

      - name: GHCR Login
        if: (github.event_name != 'pull_request')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Release Image
        if: (github.event_name == 'release')
        run: |
            tag=$(cat ./VERSION)
            echo "Tagging and releasing ${{ env.container }}:${tag}"
            docker tag  ${{ env.container }}:latest  ${{ env.container }}:${tag}
            docker tag  ${{ env.container }}:latest  ${{ env.container }}_nginx:${tag}
            docker push ${{ env.container }}:${tag}
            docker push ${{ env.container }}_nginx:${tag}

      - name: Deploy
        if: (github.event_name != 'pull_request')
        run: |
          docker push ${{ env.container }}:latest
          docker push ${{ env.container }}_nginx:latest
